version: "3"
services:
  builder:
    pull_policy: missing 
    build:
      context: "."
    image: vyos/vyos-build:sagitta
    container_name: vyos-build
    restart: "no"
    privileged: true
    security_opt:
      - apparmor:unconfined
      #- label:disable
    hostname: vyos-build
    sysctls:
      - net.ipv6.conf.lo.disable_ipv6=0
    volumes:
      - /dev:/dev
      - $PWD/source:/vyos:rw
    environment:
      - GOSU_UID=1000
      - GOSU_GID=1000
    entrypoint: ["/usr/local/bin/entrypoint.sh"]
    command: ["sleep", "infinity"]
    #command: ["1.4.0"]
