version: "2"
services:
  builder:
    image: vyos/vyos-build:crux
    privileged: true
    volumes:
      - /dev:/dev
      - /home/dpolitis/workspace/vyos-build-1.2.6:/vyos:rw
    restart: "no"
    command: ["1.2.6"]
